//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sil3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokGiris
    {
        public int Id { get; set; }
        public int MalzemeId { get; set; }
        public int GrupId { get; set; }
        public decimal BirimFiyat { get; set; }
        public decimal BirimKatSayi { get; set; }
        public decimal DolapNo { get; set; }
        public Nullable<decimal> RafNo { get; set; }
        public int DepoNo { get; set; }
    
        public virtual Depo Depo { get; set; }
        public virtual Grup Grup { get; set; }
        public virtual Malzeme Malzeme { get; set; }
    }
}
